# Generated by Django 5.1.1 on 2024-11-16 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='wea')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_wea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.wear')),
            ],
        ),
    ]
